name = "biosunlocktool-pages"
account_id = "ad170d773e79a037e28f4530fd5305a5"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[site]
bucket = "."

[[routes]]
pattern = "https://*.biosunlocktool.com/*"
script = "biosunlocktool-pages"

[vars]
DEFAULT_LOCALE = "en-US"

# Route locale mapping
[vars.LOCALES]
"biosunlocktool.com" = "en-US"
"www.biosunlocktool.com" = "en-US" 
"in.biosunlocktool.com" = "en-IN"
"de.biosunlocktool.com" = "de-DE"
"pl.biosunlocktool.com" = "pl-PL"
"af.biosunlocktool.com" = "af-ZA"
